creek0810/loveat2

- lib/auth.py
- models/user.py
- static/js/auth.js
- 登入不存在之帳號能正常顯示錯誤訊息
- 登入錯誤訊息改成中文
- navbar正常顯示帳號名稱而不是id
> Fix login nonexist

- lib/auth.py
- models/business_time.py
- views/setting_api.py
> Business time api

- models/order.py
- views/order_api.py
> History order api

- models/menu.py
- views/menu_api.py
> All menu api

- models/order.py
- views/order_api.py
> Add order api

- views/order_api.py
BREAKING CHANGE: change the post format of new order api
Before:
{
"takenAt": "2019-10-31T12:00",
"notes": "不要加番茄",
"userName": "loveateat'
"total": "500",
"content": [
{
"id": "5dd67f098f0f6afb3ebc1b68",
"category": "item",
"quantity": 1
},
{
"id": "5dd695b9fb8001b28236efb7",
"category": "combo",
"quantity": 1
}
]
}
After:
{
"takenAt": "2019-10-31T12:00",
"notes": "不要加番茄",
"total": "500",
"content": [
{
"id": "5dd67f098f0f6afb3ebc1b68",
"category": "item",
"quantity": 1
},
{
"id": "5dd695b9fb8001b28236efb7",
"category": "combo",
"quantity": 1
}
]
}
> Change post format of new order 

- models/menu.py
- views/menu_api.py
url:
- /api/menu/item
- /api/menu/combo
> Get item and combo api

- static/js/auth.js
> Change url from absolute to relative

- config_example.py
- lib/auth.py
- lib/send_email.py
- main.py
- models/business_time.py
- models/menu.py
- models/user.py
- views/menu_api.py
- views/menu_web.py
- views/order_api.py
- views/order_web.py
- views/setting_api.py
- views/setting_web.py
- views/user_api.py
- views/user_web.py
finish update user push token api
> Update token api

- models/order.py
Change datetime format of get_not_end_by_username
> Change datetime format of get_not_end_by_username

- main.py
- models/image.py
- views/root.py
> Finish image route

- lib/custom_except.py
- models/menu.py
- views/menu_api.py
url:
- /api/menu/item/delete
- /api/menu/combo/delete
- /api/menu/type/update
- /api/menu/type/new
> Finish part of edit menu api

- static/js/auth.js
> Rename function name of auth.js

- models/order.py
- views/order_api.py
> Finish todo order model and api

- static/js/lib/cart.js
- static/js/loveat2-cart.js
- total isn't updated when clear btn is clicked
- cart quantity will be uncorrect when adding the same item mulitple
times
#40
> Fix cart total update and duplicate add

- static/js/menu.js
- templates/menu.html
> Speed up loading on menu page

- static/js/loveat2-cart.js
- templates/cart.html
- templates/component/register.html
- fix the item quantity added from menu page
- set  age min value
> fix: fix cart item quantity and register age value

- models/menu.py
- models/order.py
> Enhance model

- lib/push.py
- models/order.py
- views/order_api.py
- views/root.py
- views/user_api.py
add push feat to order operation
> Finish order push

- models/business_time.py
- static/css/business-time.css
- static/js/business_time.js
- templates/business_time.html
- views/setting_web.py
feat(business_time): add the ability of setting business time
> Set business time

- models/menu.py
- static/js/loveat2-cart.js
> Fix some bug

- models/order.py
- static/js/lib/push-init.js
- templates/component/navbar.html
- views/user_api.py
- update token only when user login
- fix admin topic subscribe
- change order projection to fit correct format(content._id -> content.id)
> Fix push bug

- models/order.py
- static/js/lib/firebase-messaging-sw.js
- tests/test_order.py
- views/order_api.py
> Push to admin when order state update to doing

- models/business_time.py
- models/db.py
- models/image.py
- models/menu.py
- models/order.py
- models/user.py
- tests/conftest.py
- tests/test_item.py
- tests/test_order.py
- tests/test_setting.py
- tests/test_type.py
- tests/test_user.py
- refactor the method of connecting to db
- update testcase
> Refactor the part of connecting to db

- models/menu.py
Getting detail info of item or combo by id
> Extend projection mode to get item, combo by id

- models/order.py
add following condition
- takenAt > now
- content can't be empty
> Enhance validate for new order

- models/order.py
> Fix incorrect analysis order data

- static/js/loveat2-cart.js
- templates/cart.html
- tests/test_user.py
- views/order_web.py
- quantity error
- incompleted taken time
- show bussiness time when users choose a wrong time #53
> Enhance cart check 

- models/user.py
- static/js/auth.js
- views/user_api.py
> Auto login after user register success

- static/js/loveat2-cart.js
fix the problem that if users input the string as quantity, the sum will be NaN.
> Correct the quantity input string problem

- models/menu.py
- views/menu_api.py
return code 409 when the name of update type is duplicate
close #76
> Add status code for adding type api

- models/user.py
- static/css/profile.css
- static/js/lib/fetch-data.js
- static/js/profile.js
- templates/profile.html
- views/menu_web.py
- views/order_web.py
- views/setting_web.py
- views/user_web.py
1. profile 編輯用及觀賞用功能皆完成
2. views/..._web.py :
render_template皆增加id的參數，使profile頁面正常。
3. models/user.py :
增加get_user_info(id) 取得顧客資料。
4. static/js/lib/fetch-data.js :
增加postForm(url, data) 用來post form data。
> Finish profile feature

- static/js/lib/cart.js
- static/js/loveat2-cart.js
- templates/order-state.html
- templates/order.html
- Store item description input by users #53 
- Enhancement the order description style
- order page
- order-state page
> Store item description input by users

- models/user.py
- static/css/edit-add-combo.css
- static/css/edit-add-item.css
- templates/component/navbar.html
- views/user_web.py
修改new item/combo的css
Closes #81
> Advise new item/combo css and navbar brand

- models/menu.py
- package-lock.json
- package.json
- views/menu_api.py
- fix upload b"" image problem
- return 409 when update duplicate name on update combo, item page
close #84
> Fix menu api

- static/css/menu.css
- static/js/lib/cart.js
- static/js/loveat2-cart.js
- static/js/menu.js
- templates/menu.html
- 檢查單品的總數量是否有超過99，超過則在菜單頁面以modal提示數量最高上限為99。 #80 
- 加強部分，若種類或search結果為空，顯示提示訊息告知使用者。 #55 
Closes #55
Closes #80
> Check item quantity, enhance menu page

- .travis.yml
- models/menu.py
fix the problem when does't update name field
> Fix update item combo api

- package.json
- static/js/edit-add-combo.js
- static/js/edit-add-item.js
- static/js/menu-edit.js
- templates/edit-add-combo.html
- templates/edit-add-item.html
- templates/menu-edit.html
- views/menu_web.py
完成修改單品/套餐。
把quantity改為input。
編輯菜單的編輯種類，未分類(單品/套餐)改成不能修改/刪除。
> feat: finish update item/combo, and fix menu-edit

- static/css/profile.css
- templates/profile.html
> Profile page rwd

- lib/send_email.py
> speed up connecting to gmail

- .vscode/settings.json
- Pipfile
- static/css/cart.css
- static/js/loveat2-cart.js
- templates/cart.html
- views/order_web.py
> style: cart page rwd

- .gitignore
- .vscode/settings.json
- static/css/menu.css
- templates/component/navbar.html
- templates/menu.html
finish menu page rwd
close #41
> Menu page rwd

- static/css/cart.css
- static/css/edit-add-combo.css
- static/css/menu-edit.css
- static/js/edit-add-item.js
- templates/cart.html
- templates/menu-edit.html
finish menu-edit RWD
modify cart CSS's class name
> style: finish menu-edit RWD and modify cart CSS

- static/js/todo.js
- templates/todo.html
> Add foolproof mechanism for todo page

- Pipfile
- Pipfile.lock
- models/user.py
- static/css/user.css
- static/js/auth.js
- static/js/loveat2-cart.js
- static/js/user.js
- templates/cart.html
- templates/component/login.html
- templates/component/navbar.html
- templates/order.html
- templates/user.html
- tests/data/user.json
- tests/test_user.py
- views/order_api.py
- views/user_api.py
- views/user_web.py
as title
black list feature is finished
closes #101
> Add black list feat

- static/css/order.css
- static/js/order.js
- templates/order.html
- tests/test_order.py
- views/order_api.py
as title.
- change the api (/order/update)
closes #97
> Push by rejected order  

- .eslintrc.js
- models/db.py
- package-lock.json
- package.json
- static/js/auth.js
- static/js/bootstrap-datetimepicker.min.js
- static/js/edit-add-combo.js
- static/js/edit-add-item.js
- static/js/forget-password.js
- static/js/history.js
- static/js/lib/cart.js
- static/js/lib/firebase-messaging-sw.js
- static/js/lib/history-chart.js
- static/js/lib/push-init.js
- static/js/loveat2-cart.js
- static/js/menu-edit.js
- static/js/menu.js
- static/js/news-push.js
- static/js/order.js
- static/js/profile.js
- static/js/reset-password.js
- static/js/signature-expired.js
- static/js/todo.js
- templates/component/login.html
- templates/component/register.html
- templates/forget-password.html
- templates/reset-password.html
> Enhance form

- static/js/auth.js
- static/js/forget-password.js
- static/js/news-push.js
- static/js/reset-password.js
when enter the form page first time
after submitting form, it always refresh page
> Fix refresh first time problem
